traditional_powers:
  - Argentina
  - Brazil
  - England
  - France
  - Germany
  - Italy
  - Netherlands
  - Portugal
  - Spain
  - Uruguay

hosts:
  - Canada
  - Mexico
  - USA

high_attention:
  - Belgium
  - Colombia
  - Croatia
  - Japan
  - Korea Republic
  - Morocco
